# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todo
	pod 'R.swift', '6.1.0'
	pod 'Material', '3.1.8'
	pod 'IQKeyboardManagerSwift', '6.5.10'

  target 'todoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todoUITests' do
    # Pods for testing
  end

end
